labels:
  0: 'Undefined'
  1: 'Car'
  2: 'Truck'
  3: 'Bus'
  4: 'Other Vehicle'
  5: 'Motorcyclistr'
  6: 'Bicyclist'
  7: 'Pedestrian'
  8: 'Sign'
  9: 'Traffic Light'
  10: 'Pole'
  11: 'Construction Cone'
  12: 'Bicycle'
  13: 'Motorcycle'
  14: 'Building'
  15: 'Vegetation'
  16: 'Tree Trunk'
  17: 'Curb'
  18: 'Road'
  19: 'Lane Marker'
  20:  'Other Ground'
  21: 'Walkable'
  22: 'Sidewalk'

learning_map:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  11: 11
  12: 12
  13: 13
  14: 14
  15: 15
  16: 16
  17: 17
  18: 18
  19: 19
  20: 20
  21: 21
  22: 22